FROM node:24-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG USE_MOCK_DATA=true
ARG STRAPI_URL
ARG STRAPI_API_TOKEN
ARG STRAPI_TOKEN
ARG PUBLIC_STRAPI_URL
ARG PUBLIC_STRAPI_GRAPHQL_URL
ARG PUBLIC_SITE_URL
ARG PUBLIC_ENV=production
ARG SITE_URL
# Astro inlines these at build time, so they must be build args: a static
# site never sees runtime environment variables.
ARG PUBLIC_GTM_ID
ARG PUBLIC_WHATSAPP_PHONE
ARG STRAPI_INTERNAL_GRAPHQL_URL
ARG STRAPI_USE_MOCK

ENV USE_MOCK_DATA=$USE_MOCK_DATA
ENV STRAPI_URL=$STRAPI_URL
ENV STRAPI_API_TOKEN=$STRAPI_API_TOKEN
ENV STRAPI_TOKEN=$STRAPI_TOKEN
ENV PUBLIC_STRAPI_URL=$PUBLIC_STRAPI_URL
ENV PUBLIC_STRAPI_GRAPHQL_URL=$PUBLIC_STRAPI_GRAPHQL_URL
ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL
ENV PUBLIC_ENV=$PUBLIC_ENV
ENV SITE_URL=$SITE_URL
ENV PUBLIC_GTM_ID=$PUBLIC_GTM_ID
ENV PUBLIC_WHATSAPP_PHONE=$PUBLIC_WHATSAPP_PHONE
ENV STRAPI_INTERNAL_GRAPHQL_URL=$STRAPI_INTERNAL_GRAPHQL_URL
ENV STRAPI_USE_MOCK=$STRAPI_USE_MOCK

RUN npm run build

FROM nginx:1.27-alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
